# Generated by Django 3.0.3 on 2020-04-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200425_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
